name: Sharing Data Between Jobs Using Artifact

on:
  push:
    branches: [sharing-data]

jobs:
  upload-to-artifact:
    name: save and upload log
    steps:
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: upload log
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log

  download-from-artifact:
    needs: upload-to-artifact
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: output-log-file