name: Test Job Output
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€

on: 
  push:
    branches:
      - job-output

  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: GITHUB_OUTPUT before echo
        run: echo $GITHUB_OUTPUT

      - name: Concatenate GITHUB_OUTPUT before echo
        run: cat $GITHUB_OUTPUT
    
      - id: step1
        run: |
          echo "test=hello" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - id: step2
        run: |
          echo "test=world" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: GITHUB_OUTPUT after echo
        run: echo $GITHUB_OUTPUT

      - name: Concatenate GITHUB_OUTPUT after echo
        run: cat $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}